env:
  global:
    - secure: fSFyaJHgxk7BEjakwhjzFw9MlXyHjZ8YDsU0f+tOY35WuqyPR0xrjNDZOdClRRTHTh+5GLUwnZqlFv6TQy2Xd8ANlHnqdw+VU+lezMQF2kLATSgTOTz3scO/YUKDEZviQAdmb1HPEpD9x2CD66281a8VZwIJg2PDoGtVKkK/lMU=
    - LD_LIBRARY_PATH=/usr/local/lib
before_install:
  - yes | sudo add-apt-repository ppa:cmrx64/cargo
  - sudo apt-get update
install:
  - sudo apt-get install cargo
  - curl http://static.rust-lang.org/rustup.sh | sudo sh -
script:
  - rustc --version
  - cargo build
  - rustdoc -o doc src/lib
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
